version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysql --default_authentication_plugin=myslq_native_password
    restart: always
    environment:
        TZ: America/Sao_Paulo
        MSQL_ROOT_PASSWORD: root
        MSQL_ROOT_USER: root
        MSQL_PASSWORD: root
        MSQL_DATABASE: dbubuntu
    ports:
       - "3308:3306"
    networks:
       - outron    
  projeto-teste:
    image: projeto_teste
    restart: always
    build:
      ./
    working_dir: /projeto_teste
    environment:
        TZ: America/Sao_Paulo
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: dbubuntu
    ports:
       - 8080:8080
    command: mvn spring-boot:run
    depends_on:
       - db    
networks:
    outron:
        driver: brigde