version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysql --default_authentication_plugin=myslq_native_password
    environment:
        TZ: America/São_Paulo
        MSQL_ROOT_PASSWORD: root
        MSQL_ROOT_USER: root
        MSQL_PASSWORD: root
        MSQL_DATABASE: teste10
    ports:
       - "3307:3306"
  projeto_teste:
    image: projeto_teste
    environment:
        TZ: America/Sao_Paulo
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: teste10
    ports:
       - 80:80
    depends_on:
       - db
      